# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crawl.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_crawl_window(object):
    def setupUi(self, crawl_window):
        crawl_window.setObjectName("crawl_window")
        crawl_window.resize(1280, 720)
        crawl_window.setStyleSheet("\n"
"#window2{border-image: url(:/w2/0.jpg);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(crawl_window)
        self.centralwidget.setObjectName("centralwidget")
        self.quit = QtWidgets.QPushButton(self.centralwidget)
        self.quit.setGeometry(QtCore.QRect(185, 500, 121, 51))
        self.quit.setStyleSheet("#quit:!hover{\n"
"border-radius:10px;\n"
"background-color:rgb(255, 250, 189);\n"
"font: 18pt \"华文行楷\";\n"
"}\n"
"\n"
"#quit:hover{\n"
"border-radius:10px;\n"
"background-color:rgb(170, 255, 255);\n"
"font: 18pt \"华文行楷\";\n"
"}\n"
"#quit:pressed{padding-top:5px;\n"
"padding-left:5px;\n"
"}\n"
"\n"
"")
        self.quit.setObjectName("quit")
        self.crawl = QtWidgets.QPushButton(self.centralwidget)
        self.crawl.setGeometry(QtCore.QRect(30, 420, 121, 51))
        self.crawl.setStyleSheet("#crawl:!hover{\n"
"border-radius:10px;\n"
"background-color:rgb(255, 250, 189);\n"
"font: 18pt \"华文行楷\";\n"
"}\n"
"\n"
"#crawl:hover{\n"
"border-radius:10px;\n"
"background-color:rgb(170, 255, 255);\n"
"font: 18pt \"华文行楷\";\n"
"}\n"
"#crawl:pressed{padding-top:5px;\n"
"padding-left:5px;\n"
"}\n"
"\n"
"")
        self.crawl.setObjectName("crawl")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 130, 72, 15))
        self.label.setText("")
        self.label.setObjectName("label")
        self.cooike = QtWidgets.QLineEdit(self.centralwidget)
        self.cooike.setGeometry(QtCore.QRect(70, 120, 361, 61))
        self.cooike.setStyleSheet("font: 20pt \"隶书\";\n"
"border-radius:10px;\n"
"background-color: rgba(253, 253, 253, 50);")
        self.cooike.setText("")
        self.cooike.setObjectName("cooike")
        self.agent = QtWidgets.QLineEdit(self.centralwidget)
        self.agent.setGeometry(QtCore.QRect(70, 190, 361, 61))
        self.agent.setStyleSheet("font: 20pt \"隶书\";\n"
"border-radius:10px;\n"
"background-color: rgba(253, 253, 253, 50);")
        self.agent.setText("")
        self.agent.setObjectName("agent")
        self.url = QtWidgets.QLineEdit(self.centralwidget)
        self.url.setGeometry(QtCore.QRect(70, 50, 361, 61))
        self.url.setStyleSheet("font: 20pt \"隶书\";\n"
"border-radius:10px;\n"
"background-color: rgba(253, 253, 253, 50);")
        self.url.setText("")
        self.url.setObjectName("url")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(470, 10, 801, 701))
        self.textBrowser.setStyleSheet("font: 14pt \"宋体\";\n"
"background-color: rgba(253, 253, 253, 50);")
        self.textBrowser.setObjectName("textBrowser")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(30, 500, 121, 51))
        self.back.setStyleSheet("#back:!hover{\n"
"border-radius:10px;\n"
"background-color:rgb(255, 250, 189);\n"
"font: 18pt \"华文行楷\";\n"
"}\n"
"\n"
"#back:hover{\n"
"border-radius:10px;\n"
"background-color:rgb(170, 255, 255);\n"
"font: 18pt \"华文行楷\";\n"
"}\n"
"#back:pressed{padding-top:5px;\n"
"padding-left:5px;\n"
"}\n"
"\n"
"")
        self.back.setObjectName("back")
        self.file_name = QtWidgets.QLineEdit(self.centralwidget)
        self.file_name.setGeometry(QtCore.QRect(70, 260, 361, 61))
        self.file_name.setStyleSheet("font: 20pt \"华文行楷\";\n"
"border-radius:10px;\n"
"background-color: rgba(253, 253, 253, 50);")
        self.file_name.setText("")
        self.file_name.setObjectName("file_name")
        self.file_csv = QtWidgets.QLineEdit(self.centralwidget)
        self.file_csv.setGeometry(QtCore.QRect(70, 330, 361, 61))
        self.file_csv.setStyleSheet("font: 20pt \"华文行楷\";\n"
"border-radius:10px;\n"
"background-color: rgba(253, 253, 253, 50);")
        self.file_csv.setText("")
        self.file_csv.setObjectName("file_csv")
        self.hot = QtWidgets.QPushButton(self.centralwidget)
        self.hot.setGeometry(QtCore.QRect(185, 420, 121, 51))
        self.hot.setStyleSheet("#hot:!hover{\n"
"border-radius:10px;\n"
"background-color:rgb(255, 250, 189);\n"
"font: 18pt \"华文行楷\";\n"
"}\n"
"\n"
"#hot:hover{\n"
"border-radius:10px;\n"
"background-color:rgb(170, 255, 255);\n"
"font: 18pt \"华文行楷\";\n"
"}\n"
"#hot:pressed{padding-top:5px;\n"
"padding-left:5px;\n"
"}\n"
"\n"
"")
        self.hot.setObjectName("hot")
        self.sentiments = QtWidgets.QPushButton(self.centralwidget)
        self.sentiments.setGeometry(QtCore.QRect(340, 420, 121, 51))
        self.sentiments.setStyleSheet("#sentiments:!hover{\n"
"border-radius:10px;\n"
"background-color:rgb(255, 250, 189);\n"
"font: 18pt \"华文行楷\";\n"
"}\n"
"\n"
"#sentiments:hover{\n"
"border-radius:10px;\n"
"background-color:rgb(170, 255, 255);\n"
"font: 18pt \"华文行楷\";\n"
"}\n"
"#sentiments:pressed{padding-top:5px;\n"
"padding-left:5px;\n"
"}\n"
"\n"
"")
        self.sentiments.setObjectName("sentiments")
        self.bg_gif = QtWidgets.QLabel(self.centralwidget)
        self.bg_gif.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.bg_gif.setText("")
        self.bg_gif.setObjectName("bg_gif")
        self.bg_gif.raise_()
        self.quit.raise_()
        self.crawl.raise_()
        self.label.raise_()
        self.cooike.raise_()
        self.agent.raise_()
        self.url.raise_()
        self.textBrowser.raise_()
        self.back.raise_()
        self.file_name.raise_()
        self.file_csv.raise_()
        self.hot.raise_()
        self.sentiments.raise_()
        crawl_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(crawl_window)
        QtCore.QMetaObject.connectSlotsByName(crawl_window)

    def retranslateUi(self, crawl_window):
        _translate = QtCore.QCoreApplication.translate
        crawl_window.setWindowTitle(_translate("crawl_window", "emotional damage"))
        self.quit.setText(_translate("crawl_window", "退出"))
        self.crawl.setText(_translate("crawl_window", "爬取"))
        self.cooike.setPlaceholderText(_translate("crawl_window", "cooike"))
        self.agent.setPlaceholderText(_translate("crawl_window", "agent"))
        self.url.setPlaceholderText(_translate("crawl_window", "url"))
        self.back.setText(_translate("crawl_window", "返回"))
        self.file_name.setPlaceholderText(_translate("crawl_window", "文件夹名"))
        self.file_csv.setPlaceholderText(_translate("crawl_window", "文件名"))
        self.hot.setText(_translate("crawl_window", "热词"))
        self.sentiments.setText(_translate("crawl_window", "情感"))
