# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_info(object):
    def setupUi(self, info):
        info.setObjectName("info")
        info.resize(1280, 720)
        info.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(info)
        self.centralwidget.setObjectName("centralwidget")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(10, 660, 121, 51))
        self.back.setStyleSheet("#back:!hover{\n"
"border-radius:10px;\n"
"background-color:transparent;\n"
"font: 18pt \"华文行楷\";\n"
"}\n"
"\n"
"#back:hover{\n"
"border-radius:10px;\n"
"background-color:rgb(170, 255, 255);\n"
"font: 18pt \"华文行楷\";\n"
"}\n"
"#back:pressed{padding-top:5px;\n"
"padding-left:5px;\n"
"}\n"
"\n"
"")
        self.back.setObjectName("back")
        self.quit = QtWidgets.QPushButton(self.centralwidget)
        self.quit.setGeometry(QtCore.QRect(140, 660, 121, 51))
        self.quit.setStyleSheet("#quit:!hover{\n"
"border-radius:10px;\n"
"background-color:transparent;\n"
"font: 18pt \"华文行楷\";\n"
"}\n"
"\n"
"#quit:hover{\n"
"border-radius:10px;\n"
"background-color:rgb(170, 255, 255);\n"
"font: 18pt \"华文行楷\";\n"
"}\n"
"#quit:pressed{padding-top:5px;\n"
"padding-left:5px;\n"
"}\n"
"\n"
"")
        self.quit.setObjectName("quit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()
        self.back.raise_()
        self.quit.raise_()
        info.setCentralWidget(self.centralwidget)

        self.retranslateUi(info)
        QtCore.QMetaObject.connectSlotsByName(info)

    def retranslateUi(self, info):
        _translate = QtCore.QCoreApplication.translate
        info.setWindowTitle(_translate("info", "hhhhhhdu"))
        self.back.setText(_translate("info", "返回"))
        self.quit.setText(_translate("info", "退出"))
