# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainwindow(object):
    def setupUi(self, mainwindow):
        mainwindow.setObjectName("mainwindow")
        mainwindow.resize(1280, 720)
        mainwindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        mainwindow.setStyleSheet("#window1{border-image: url(:/back/preview.jpg);}\n"
"")
        self.centralwidget = QtWidgets.QWidget(mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.weibo = QtWidgets.QPushButton(self.centralwidget)
        self.weibo.setGeometry(QtCore.QRect(100, 600, 181, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weibo.sizePolicy().hasHeightForWidth())
        self.weibo.setSizePolicy(sizePolicy)
        self.weibo.setMinimumSize(QtCore.QSize(181, 0))
        self.weibo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.weibo.setAutoFillBackground(False)
        self.weibo.setStyleSheet("#weibo:!hover{\n"
"border-radius:10px;\n"
"background-color:rgb(255, 250, 189);\n"
"font: 28pt \"华文行楷\";\n"
"}\n"
"\n"
"#weibo:hover{\n"
"border-radius:10px;\n"
"background-color:rgb(170, 255, 255);\n"
"font: 28pt \"华文行楷\";\n"
"}\n"
"#weibo:pressed{padding-top:5px;\n"
"padding-left:5px;\n"
"}\n"
"\n"
"")
        self.weibo.setFlat(False)
        self.weibo.setObjectName("weibo")
        self.info = QtWidgets.QPushButton(self.centralwidget)
        self.info.setGeometry(QtCore.QRect(550, 600, 150, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info.sizePolicy().hasHeightForWidth())
        self.info.setSizePolicy(sizePolicy)
        self.info.setStyleSheet("#info:!hover{\n"
"border-radius:10px;\n"
"background-color:rgb(255, 250, 189);\n"
"font: 28pt \"华文行楷\";\n"
"}\n"
"\n"
"#info:hover{\n"
"border-radius:10px;\n"
"background-color:rgb(170, 255, 255);\n"
"font: 28pt \"华文行楷\";\n"
"}\n"
"#info:pressed{padding-top:5px;\n"
"padding-left:5px;\n"
"}\n"
"\n"
"")
        self.info.setObjectName("info")
        self.quit = QtWidgets.QPushButton(self.centralwidget)
        self.quit.setGeometry(QtCore.QRect(1000, 600, 150, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quit.sizePolicy().hasHeightForWidth())
        self.quit.setSizePolicy(sizePolicy)
        self.quit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.quit.setAutoFillBackground(False)
        self.quit.setStyleSheet("#quit:!hover{\n"
"border-radius:10px;\n"
"background-color:rgb(255, 250, 189);\n"
"font: 28pt \"华文行楷\";\n"
"}\n"
"\n"
"#quit:hover{\n"
"border-radius:10px;\n"
"background-color:rgb(170, 255, 255);\n"
"font: 28pt \"华文行楷\";\n"
"}\n"
"#quit:pressed{padding-top:5px;\n"
"padding-left:5px;\n"
"}\n"
"\n"
"")
        self.quit.setObjectName("quit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()
        self.weibo.raise_()
        self.info.raise_()
        self.quit.raise_()
        mainwindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainwindow)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)

    def retranslateUi(self, mainwindow):
        _translate = QtCore.QCoreApplication.translate
        mainwindow.setWindowTitle(_translate("mainwindow", "MainWindow"))
        self.weibo.setText(_translate("mainwindow", "微博"))
        self.info.setText(_translate("mainwindow", "info"))
        self.quit.setText(_translate("mainwindow", "退出"))
